### ISSUE TITLE
add audio autoplay on items/show

### ISSUE THREAD

**Issue by elbidone** [meumobi/RImobi#10]
Between title and description add an audio player with the first audio/mpeg of medias.
Use attributes and styles as described below

```html
<audio controls autoplay>
  <source ng-src="http://cielo.riweb.com.br/Download.aspx?Arquivo=cVHWLHtaRy3hFgnERsbCjg==" type="audio/mpeg" />
  Your browser does not support the audio element.
</audio>
```

with following style
```css
/* Media */
audio { width:100%; max-width:100%; box-sizing: border-box; display: inline-block; }

audio { margin-top:10px; }
```

![news_feed_-_rss___meumobi_investors](https://cloud.githubusercontent.com/assets/9011612/7508162/a920703a-f451-11e4-98fc-b4a678133d4c.png)
