### ISSUE TITLE
pagination is missing on Triunfo

### ISSUE THREAD

**Issue by elbidone** [meumobi/RImobi#15]

**Comment by t4deu** [comment]
It isn't missing, it's hidden.
By the custom css:
```css
.pagination{display:none}
```
